# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra", "> 2.0.2"

gem "haml",  "~> 5.0"
gem "hutch", "~> 0.25"
gem "puma",  "~> 4.2"
gem "rake",  "~> 12"

group :development, :test do
  gem "awesome_print", "~> 1.8"
  gem "json_spec",     "~> 1.1"
  gem "rspec",         "~> 3.7"
  gem "rubocop", "~> 0.93", require: false
  gem "rubocop-rspec", "~> 1.22"
  # gem "rack-test"
  # gem "webmock"
end
