require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
      - config.ru

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 125

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 8

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*_spec.rb'
    - 'spec/system/**/*_spec.rb'

RSpec/ExampleLength:
  Max: 20

RSpec/NamedSubject:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 15

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%W': '()'

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: percent
