# frozen_string_literal: true

require "awesome_print"
require "rake"

desc "Opens the console and loads the app"
task :console do
  puts "Console with the app and awesome_print loaded:"
  ARGV.clear
  require "irb"
  require "ap"
  require_relative "app.rb"
  IRB.start
end

desc "Starts the hutch process to create and consume the queues"
task :hutch do
  sh 'bundle exec hutch --require hutch_consumer_config.rb'
end
